### ISSUE TITLE
Fix parsing strings with slashes

### ISSUE THREAD

**Issue by WillTheVideoMan** [WillTheVideoMan/raw-media-server#5]
Properly encode all requests to lastfm, as artists with slashes (e.g. Au/Ra) return a silly result.

**Comment by ConnorPowell** [comment]
It seems to work fine if you just do "AuRa" as the artist, if I've got the correct artist that is. Although if you need a "/" couldn't it just be URI encoded to "%2F" in the URL, without needing any changes to the server?

**Comment by WillTheVideoMan** [comment]
I think the issue lies with encoding the params for the internal requests to lastFM. 

Even if you include the properly encoded character on requests to media2, the lastfm request dosen't get properly encoded and hence fails (or at least dosen't get a proper artist image).

**Comment by ConnorPowell** [comment]
I see, does Axios automatically encode special characters when it sends the request to LastFM? If not I imagine that would be the only change that'd be required.

**Comment by WillTheVideoMan** [comment]
Funnily enough it **should** encode the params automatically... So retrospectively I am not sure why the request fails to return a meaningful response.

Needs a bit of investigation.

**Comment by ConnorPowell** [comment]
Postman is a really good tool for interacting with APIs - https://www.getpostman.com/

**Comment by WillTheVideoMan** [comment]
Interesting find: behaviour is normal and returns a meaningful response when running locally. 

Recently I added the 'allowencodedslashes noDecode' directive to the media2-ssl server block running on apache2. 

This fixed an issue where Apache would return a 404 if any encoded slashes were present in the URL at all. 

Could the Apache reverse proxy be interfering?

**Comment by WillTheVideoMan** [comment]
https://stackoverflow.com/a/9933890

**Comment by WillTheVideoMan** [comment]
Updated apache config, issue now fixed.
